from docx import Document
from pathlib import Path

path = Path(r"G:\New_CRC_Platelet\24_制作投稿文件包\manuscript\CRC_PLEK_myeloid_state_Main_Manuscript.docx")
doc = Document(path)

replacements = {
"The data favor a compositional explanation. PLEK was detected in most tumor-tissue neutrophils but was also common in monocytes, macrophages, and dendritic cells. Its donor-level association with neutrophil fraction persisted with study-clustered errors, a study random intercept, and every leave-one-study-out analysis. The lack of gene overlap with the marker module excludes direct self-inclusion, but shared myeloid ancestry and variation in cell composition can still produce the observed covariance. The wide PLEK prediction interval further indicates that its effect size depends on cohort and tissue context.":
"The data favor a compositional explanation. PLEK was detected in most tumor-tissue neutrophils but was also common in monocytes, macrophages, and dendritic cells. Its donor-level association with neutrophil fraction persisted with study-clustered errors, a study random intercept, and every leave-one-study-out analysis. This study does not present myeloid expression of PLEK as a new biological finding. The absence of gene overlap between PLEK and the marker module excludes direct mathematical self-inclusion, but it does not remove covariance generated by shared hematopoietic ancestry or changing myeloid-cell proportions. Accordingly, the PLEK correlation is best interpreted as evidence that the nominally platelet-related composite score contains a broad myeloid compositional component, not as evidence of a newly discovered PLEK-neutrophil program. The wide PLEK prediction interval further indicates that the magnitude of this component is cohort- and tissue-context dependent.",
"The analysis illustrates why a reproducible bulk signature need not retain its assigned cellular identity. Matched random modules and leave-one-cohort-out analyses argued against a generic small-module artifact, whereas single-cell and spatial data changed the biological reading of the signal. The negative results were equally consequential: they ruled out development of the 13-gene score as a prognostic model and prevented a cohort-dependent endothelial association from becoming a general claim.":
"The incremental information therefore lies in reclassifying the composite state rather than rediscovering that PLEK is expressed in myeloid cells. Across independent CRC cohorts and data modalities, a score assembled as platelet related did not behave as a measure of platelet abundance or prognosis; instead, its reproducible bulk association was largely attributable to a known PLEK-rich myeloid component, with weaker and source-ambiguous contribution from PPBP and no stable contribution from PF4. Matched random modules and leave-one-cohort-out analyses argued against a generic small-module artifact, whereas single-cell and spatial analyses defined the limits of cellular attribution. This provides a practical interpretive rule for CRC transcriptomic studies: platelet-related bulk scores require explicit leukocyte-composition and source auditing before they are used as evidence of platelet biology.",
"In conclusion, the platelet-related composite state contains a reproducible PLEK-associated myeloid component with neutrophil-related enrichment. PPBP is a weaker, source-ambiguous bulk component, and PF4 contributes no stable independent association. The state is neither prognostic nor platelet-specific, and its spatial support is limited. Its value lies in showing how cross-cohort and cell-context analyses can revise the biological interpretation of a bulk transcriptional signal.":
"In conclusion, this study does not identify a new function or cellular specificity for PLEK. It shows that a nominally platelet-related CRC tissue signature is substantially reclassified by a PLEK-rich myeloid compositional component with neutrophil-related enrichment. PPBP is a weaker, source-ambiguous bulk component, and PF4 contributes no stable independent association. The composite state is neither prognostic nor platelet-specific, and its spatial support is limited. Its value is methodological and interpretive: cross-cohort and cell-context analyses can prevent a reproducible bulk signal from being assigned an unsupported cellular identity or mechanism."
}

for p in doc.paragraphs:
    if p.text in replacements:
        p.text = replacements[p.text]

for table in doc.tables:
    for row in table.rows:
        for cell in row.cells:
            if cell.text.strip() == "Primary driver; modified HK":
                cell.text = "Largest statistical contributor; modified HK"

doc.save(path)
print(path)
